name: Run Acceptance Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run acceptance test (generate tree and check output)
        run: |
          npm start -- --layers 8 --output test-tree.txt
          if [ ! -f test-tree.txt ]; then
            echo "❌ Acceptance test failed: output file not created"
            exit 1
          fi
          if grep -q "winter" test-tree.txt; then
            echo "❌ Acceptance test failed: invalid output"
            exit 1
          fi
          echo "✅ Acceptance test passed"
